language: r
os: linux
dist: xenial
cache: packages
warnings_are_errors: true
r_check_args: --no-manual # Workaround error compiling PDF manual
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: FALSE

git:
  depth: 1

r_packages:
 - devtools # imports pkgload, remotes, roxygen2, testthat

before_script:
  - R -e "pkgload::load_all(); devtools::document()"

jobs:
  include:
    - r: release
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
#      r_binary_packages:
#       - ape
#       - devtools
#       - phangorn
#       - Rcpp
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        cleanup: false
        skip_cleanup: true
        local_dir: "docs"
        keep-history: true
        on:
          branch: master
    - r: 3.6.0 # Phangorn requires R 3.6.0
      branches:
        only: master
      after_success:
        - Rscript -e "covr::codecov()"
    - r: devel
      r_check_args: --as-cran --no-manual
      env:
         - _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
         - _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
         - R_COMPILE_AND_INSTALL_PACKAGES: 'never'
         - _R_CHECK_THINGS_IN_CHECK_DIR_: false
         - R_REMOTES_STANDALONE: true
         - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
         - _R_CHECK_FORCE_SUGGESTS_: true
         - _R_CHECK_CRAN_INCOMING_USE_ASPELL_: true
    - os: osx
      branches:
        only: master
      r: release
      before_install:
      - sudo tlmgr install doi titling hyperref
  allow_failures:
    - os: osx
  fast_finish: true
