language: R
cache: packages
sudo: required # required if r_binary_packages; false otherwise
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual

git:
  depth: 1

r_binary_packages:
 - ape
 - covr
 - devtools
 - testthat

before_script:
  - R -e "devtools::load_all(); devtools::document()"

matrix:
  include:
    - r: 3.4.0
    - r: release
      before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        local_dir: "docs"
        keep-history: true
        on: 
          branch: master
    - r: devel
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      r: release
      r_packages:
        - ape
        - devtools
        - testthat
      before_install:
      - brew install cairo
      - sudo tlmgr install doi titling hyperref
#  allow_failures:
