# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_newick <- function(edge) {
    .Call(`_TreeTools_as_newick`, edge)
}

drop_tip <- function(preorder, drop) {
    .Call(`_TreeTools_drop_tip`, preorder, drop)
}

num_to_parent <- function(n, nTip) {
    .Call(`_TreeTools_num_to_parent`, n, nTip)
}

random_parent <- function(nTip, seed) {
    .Call(`_TreeTools_random_parent`, nTip, seed)
}

edge_to_num <- function(parent, child, nTip) {
    .Call(`_TreeTools_edge_to_num`, parent, child, nTip)
}

minimum_spanning_tree <- function(order) {
    .Call(`_TreeTools_minimum_spanning_tree`, order)
}

cpp_edge_to_splits <- function(edge, nTip) {
    .Call(`_TreeTools_cpp_edge_to_splits`, edge, nTip)
}

tips_in_splits <- function(splits) {
    .Call(`_TreeTools_tips_in_splits`, splits)
}

edge_to_rooted_shape <- function(parent, child, nTip) {
    .Call(`_TreeTools_edge_to_rooted_shape`, parent, child, nTip)
}

rooted_shape_to_edge <- function(shape, nTip) {
    .Call(`_TreeTools_rooted_shape_to_edge`, shape, nTip)
}

