# Address Sanitizer: Replicate CRAN's gcc-ASAN 'Additional Test'
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - '**asan**'
    paths:
      - '.github/workflows/ASan.yml'
      - 'src/**'
      - 'inst/include/**'
      - 'memcheck/**'
      - 'tests/testthat/**.R'
      - 'vignettes/**.Rmd'
  pull_request:
    paths:
      - '.github/workflows/ASan.yml'
      - 'src/**'
      - 'inst/include/**'
      - 'memcheck/**'
      - 'tests/testthat/**.R'
      - 'vignettes/**.Rmd'

name: gcc-ASAN

jobs:
  mem-check:
    runs-on: ubuntu-latest

    name: AddressSanitizer ${{ matrix.config.test }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {test: 'tests'}
          - {test: 'examples'}
          - {test: 'vignettes'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      USING_ASAN: true
      STRINGI_DISABLE_PKG_CONFIG: true
      BIOCONDUCTOR_USE_CONTAINER_REPOSITORY: FALSE # For stringi
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ASAN_OPTIONS: verify_asan_link_order=0

    steps:
      - uses: actions/checkout@v4

      - name: Initialize ASan configuration
        run: |
          export LD_PRELOAD=$(gcc -print-file-name=libasan.so)

          echo "PKG_CFLAGS = -g -fsanitize=address -fno-omit-frame-pointer" > src/Makevars
          echo "PKG_CXXFLAGS = -g -fsanitize=address -fno-omit-frame-pointer" >> src/Makevars

          mkdir ~/.R
          echo "LDFLAGS = -g -fsanitize=address -fno-omit-frame-pointer" >> ~/.R/Makevars

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release # CRAN uses devel, but takes ages to load deps.

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: "'soft'"
          needs: |
            memcheck

      - name: Install package
        run: |
          cd ..
          R CMD build --no-build-vignettes --no-manual --no-resave-data TreeTools
          R CMD INSTALL TreeTools*.tar.gz
          cd TreeTools

      - name: ASAN - memcheck ${{ matrix.config.test }}
        run: |
          Rscript memcheck/${{ matrix.config.test }}.R
