name: Benchmark

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  benchmark_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'devtools::install_dev_deps(dependencies = TRUE)'

      - name: Install package with -O3 flag
        run: R CMD INSTALL . --preclean --clean --byte-compile --no-multiarch --no-resave-data -O3

      - name: Install TreeDist
        run: |
          Rscript -e 'install.packages("TreeDist")'
        
      - name: Run benchmarks for PR
        run: Rscript benchmark/_run_benchmarks.R
        shell: bash

      - name: Upload PR benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: pr-benchmark-results
          path: benchmark_results.rds

  benchmark_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'devtools::install_dev_deps(dependencies = TRUE)'

      - name: Install package with -O3 flag
        run: R CMD INSTALL . --preclean --clean --byte-compile --no-multiarch --no-resave-data -O3

      - name: Install TreeDist
        run: |
          Rscript -e 'install.packages("TreeDist")'
        
      - name: Run benchmarks for main branch
        run: Rscript benchmark/_run_benchmarks.R
        shell: bash

      - name: Upload main benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: main-benchmark-results
          path: benchmark_results.rds

  compare_benchmarks:
    runs-on: ubuntu-latest
    needs: [benchmark_pr, benchmark_main]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages("microbenchmark")'
          Rscript -e 'install.packages("gh")'

      - name: Download PR benchmark results
        uses: actions/download-artifact@v4
        with:
          name: pr-benchmark-results
          path: .

      - name: Download main benchmark results
        uses: actions/download-artifact@v4
        with:
          name: main-benchmark-results
          path: .

      - name: Compare benchmarks and comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          Rscript benchmark/_compare_results.R
        shell: bash
