on:
  push:
    branches:
      - main
      - master
    paths:
      - 'DESCRIPTION'
      - '**codemeta.yml'

name: codemeta
      
jobs:
  codemeta:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
     
      - name: Set up R dependencies (Windows)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            metadata

      - name: Build metadata
        run: "codemeta::write_codemeta()"
        shell: Rscript {0}
        
      - name: Deploy metadata
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add codemeta.json
          git commit -m "Update codemeta.json"
          git fetch
          git pull
          git push

