on:
  push:
    branches:
      - main
      - master
    paths:
      - 'DESCRIPTION'
      - '**pkgdown.yml'
      - '*.md'
      - 'inst/CITATION'
      - 'inst/*.bib'
      - 'man/**.R'
      - 'man-roxygen/**.R'
      - 'vignettes/**.Rmd'

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(
            dependencies = c('soft', 'Config/Needs/website')),
            ".github/depends.Rds", version = 2
          )
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install Mac OS dependencies
        run: |
          brew install libgit2
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Install dependencies
        run: |
          remotes::install_deps(
            dependencies = c('soft', 'Config/Needs/website')
          )
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Build and deploy documentation
        run: |
          pkgdown::deploy_to_branch(new_process = FALSE)
          if (length(warnings()) > 0) {
            stop("Fail on warning")
          }
        shell: Rscript {0}
