on:
  push:
    branches:
      - main
      - master
    paths:
      - 'DESCRIPTION'
      - '**pkgdown.yml'
      - '*.md'
      - 'inst/CITATION'
      - 'inst/*.bib'
      - 'man/**.R'
      - 'man-roxygen/**.R'
      - 'vignettes/**.Rmd'

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: ms609/actions/pkgdown@main
