# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 4'  # Thursdays, 4am
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-24.04, r: '3.6', rspm: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"}
          - {os: ubuntu-24.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"}
          - {os: ubuntu-24.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"}

    env:
      _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      _R_CHECK_THINGS_IN_CHECK_DIR_: false
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REALLY_FORCE_SYMBOLS: true # Until R4.3
      _R_CHECK_CRAN_INCOMING_USE_ASPELL_: false # Set to true when can figure how to install aspell on Windows
      RSPM: ${{ matrix.config.rspm }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Temporarily bump package version
        run: |
          old_version=$(grep "Version:" DESCRIPTION | awk '{print $2}')
          if [[ $(echo "$old_version" | tr -cd '.' | wc -c) -eq 2 ]]; then
            new_version="${old_version}.9999"
            if [[ "$RUNNER_OS" == "macOS" ]]; then
              sed -i "" "s/Version: .*/Version: ${new_version}/" DESCRIPTION
            else
              sed -i "s/Version: .*/Version: ${new_version}/" DESCRIPTION
            fi
          fi
          echo "Current package version is now: $(grep "Version:" DESCRIPTION | awk '{print $2}')"
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
        
      - name: Install apt packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install texlive-latex-base texlive-fonts-recommended
          
      - name: Install libgsl-dev (R 3.6)
        if: matrix.config.r == '3.6' && runner.os == 'Linux'
        run: |
          sudo apt-get install libgsl-dev
      
      - name: Set up R dependencies (Windows)
        if: runner.os == 'Windows'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            check
            coverage
                  
      - name: Set up R dependencies (R 3.6)
        if: matrix.config.r == '3.6'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rvest@1.0.4
            tzdb@0.4.0
            gh@1.4.1
            svglite@2.1.3
            scales@1.3.0
            magick@2.8.5
            purrr@1.0.2
            bench@1.1.3
            waldo@0.5.3
            testthat@3.2.1
            vdiffr@1.0.7
            cpp11@0.5.0
            httr2@1.0.1
            downlit@0.4.3
            pkgdown@2.0.9
            profvis@0.3.8
            gtable@0.3.5
            evaluate@0.23
            knitr@1.45
            phangorn@2.7.1
            Rfast@1.9.8
            rjson@0.2.20
            usethis@3.1.0
            XML@3.99-0.3
            TreeDist=?ignore-before-r=4.0.0
            TreeSearch=?ignore-before-r=4.0.0
          needs: |
            check
      
      - name: Set up R dependencies
        if: matrix.config.r != '3.6' && runner.os != 'Windows'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pandoc-version: "latest"
          needs: |
            check
          extra-packages: |
            phangorn=?ignore-before-r=4.1.0

      - name: Check package
        uses: r-lib/actions/check-r-package@v2

      - name: Code coverage
        if: runner.os == 'Windows'
        run: |
          covr::codecov()
        shell: Rscript {0}
        
      - name: Notify on failure
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 170,
              body: 'Scheduled workflow has failed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            });
