# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**R-CMD-check.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: '3.6', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      _R_CHECK_THINGS_IN_CHECK_DIR_: false
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REALLY_FORCE_SYMBOLS: true
      _R_CHECK_CRAN_INCOMING_USE_ASPELL_: false # Set to true when can figure how to install aspell on Windows
      RSPM: ${{ matrix.config.rspm }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
        
      - name: Install apt packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install texlive-latex-base texlive-fonts-recommended libcurl4-openssl-dev
        
      - name: Set up R dependencies (Windows)
        if: runner.os == 'Windows'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            check
            coverage
                  
      - name: Set up R dependencies (R 3.6)
        if: matrix.config.r == '3.6'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            ade4@1.7-22
            ape@5.8
            askpass@1.2.1
            backports@1.5.0
            base@*@3.6.3
            base64enc@0.1-3
            base64url@1.4
            bench@1.1.3
            BiocGenerics@0.32.0
            Biostrings@2.54.0
            bit@4.5.0.1
            bit64@4.5.2
            bitops@1.0-9
            boot@1.3-24
            brew@1.0-10
            brio@1.1.5
            bslib@0.8.0
            cachem@1.1.0
            callr@3.7.6
            class@7.3-15
            cli@3.6.3
            clipr@0.8.0
            cluster@2.1.0
            codetools@0.2-16
            colorspace@2.1-1
            commonmark@1.9.2
            compiler@3.6.3
            covr@3.6.4
            cpp11@0.5.0
            crayon@1.5.3
            credentials@2.0.2
            curl@6.0.1
            data.table@1.16.4
            datasets@3.6.3
            DBI@1.2.3
            decor@1.0.2
            desc@1.4.3
            devtools@2.4.5
            diffobj@0.3.5
            diffviewer@0.1.2
            digest@0.6.37
            docopt@0.7.1
            downlit@0.4.3
            ellipsis@0.3.2
            evaluate@0.23
            fansi@1.0.6
            farver@2.1.2
            fastmap@1.2.0
            fastmatch@1.1-4
            filehash@2.4-6
            fontawesome@0.5.3
            foreign@0.8-75
            formatR@1.14
            fs@1.6.5
            gert@2.1.4
            ggplot2@3.5.1
            gh@1.4.1
            gifski@1.32.0-1
            gitcreds@0.1.2
            glue@1.8.0
            graphics@3.6.3
            grDevices@3.6.3
            grid@3.6.3
            gridSVG@1.7-5
            gtable@0.3.5
            here@1.0.1
            highr@0.11
            hms@1.1.3
            htmltools@0.5.8.1
            htmlwidgets@1.6.4
            httpuv@1.6.15
            httr@1.4.7
            httr2@1.0.1
            hunspell@3.0.5
            igraph@2.1.2
            ini@0.3.1
            IRanges@2.20.2
            isoband@0.2.7
            jose@1.2.1
            jpeg@0.1-10
            jquerylib@0.1.4
            jsonlite@1.8.9
            JuliaCall@0.17.6
            KernSmooth@2.23-16
            knitr@1.45
            labeling@0.4.3
            later@1.4.1
            lattice@0.20-38
            lazyeval@0.2.2
            lifecycle@1.0.4
            lobstr@1.1.2
            magick@2.8.5
            magrittr@2.0.3
            markdown@1.13
            MASS@7.3-51.5
            MassSpecWavelet@1.52.0
            Matrix@1.2-18
            memoise@2.0.1
            methods@3.6.3
            mgcv@1.8-31
            mime@0.12
            miniUI@0.1.1.1
            mockery@0.4.4
            multitaper@1.0-17
            munsell@0.5.1
            nlme@3.1-144
            nnet@7.3-12
            openssl@2.2.2
            packrat@0.9.2
            pak@0.8.0
            parallel@3.6.3
            phangorn@2.7.1
            pillar@1.9.0
            pixmap@0.4-13
            pkgbuild@1.4.5
            pkgconfig@2.0.3
            pkgdown@2.0.9
            pkgload@1.4.0
            PKI@0.1-14
            PlotTools@0.3.1
            png@0.1-8
            praise@1.0.0
            prettydoc@0.4.1
            prettyunits@1.2.0
            processx@3.8.4
            profmem@0.6.0
            profvis@0.3.8
            progress@1.2.3
            promises@1.3.2
            ps@1.8.1
            purrr@1.0.2
            quadprog@1.5-8
            R.cache@0.16.0
            R.methodsS3@1.8.2
            R.oo@1.27.0
            R.utils@2.12.3
            R6@2.5.1
            ragg@1.3.3
            rappdirs@0.3.3
            rbibutils@2.3
            rcmdcheck@1.4.0
            RColorBrewer@1.1-3
            Rcpp@1.0.13-1
            RcppArmadillo@14.2.2-1
            RcppTOML@0.2.2
            RcppZiggurat@0.1.6
            RCurl@1.98-1.16
            Rdpack@2.6.2
            rematch2@2.1.2
            remotes@2.5.0
            renv@1.0.11
            reticulate@1.40.0
            rex@1.2.1
            Rfast@1.9.8
            rgl@1.3.14
            rjson@0.2.20
            rlang@1.1.4
            rmarkdown@2.29
            roxygen2@7.3.2
            rpart@4.1-15
            rprojroot@2.0.4
            rsconnect@1.3.3
            rstudioapi@0.17.1
            rticles@0.27
            rversions@2.1.2
            rvest@1.0.4
            S4Vectors@0.24.4
            sass@0.4.9
            scales@1.3.0
            secretbase@1.0.3
            segmented@2.1-3
            selectr@0.4-2
            seqinr@4.2-36
            seqLogo@1.52.0
            sessioninfo@1.2.2
            shiny@1.9.1
            showtext@0.9-7
            showtextdb@3.0
            sourcetools@0.1.7-1
            sp@2.1-4
            spatial@7.3-11
            spelling@2.3.1
            splines@3.6.3
            stats@3.6.3
            stats4@3.6.3
            stringi@1.8.4
            stringr@1.5.1
            styler@1.10.3
            survival@3.1-8
            svglite@2.1.3
            sys@3.4.3
            sysfonts@0.8.9
            systemfonts@1.1.0
            targets@1.9.1
            tcltk@3.6.3
            testit@0.13
            testthat@3.2.1
            textshaping@0.4.1
            tibble@3.2.1
            tidyselect@1.2.1
            tikzDevice@0.12.6
            tinytest@1.4.1
            tinytex@0.54
            tools@3.6.3
            urlchecker@1.0.1
            usethis@3.1.0
            utf8@1.2.4
            utils@3.6.3
            vctrs@0.6.5
            vdiffr@1.0.7
            viridisLite@0.4.2
            waldo@0.5.3
            waveslim@1.8.5
            webfakes@1.3.1
            webshot@0.5.5
            whisker@0.4.1
            withr@3.0.2
            xfun@0.49
            XML@3.99-0.3
            xml2@1.3.6
            xopen@1.0.1
            xtable@1.8-4
            XVector@0.26.0
            yaml@2.3.10
            zip@2.3.1
            zlibbioc@1.32.0
          needs: |
            check
      
      - name: Set up R dependencies
        if: matrix.config.r != '3.6' && runner.os != 'Windows'
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: |
            check
          extra-packages: |
            phangorn=?ignore-before-r=4.1.0

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Check package
        uses: r-lib/actions/check-r-package@v2

      - name: Code coverage
        if: runner.os == 'Windows'
        run: |
          covr::codecov()
        shell: Rscript {0}
