on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/rchk.yml'
      - 'src/**'
      - 'inst/include/**'
      - 'memcheck/**'
      - 'tests/testthat/**.R'
      - 'vignettes/**.Rmd'
  pull_request:
    paths:
      - '.github/workflows/rchk.yml'
      - 'src/**'
      - 'inst/include/**'
      - 'memcheck/**'
      - 'tests/testthat/**.R'
      - 'vignettes/**.Rmd'

name: rchk

jobs:  
  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
    - uses: actions/checkout@v2
      
    - uses: r-lib/actions/run-rchk@v2
      with:
        setup-only: true
        
    - name: Install `pak` from source
      run: |
        install.packages("pak", repos = "https://cran.rstudio.com/")
      shell: Rscript {0}
      
    - uses: r-lib/actions/setup-r-dependencies@v1
      with:
        cache-version: rchk-1
    - uses: r-lib/actions/run-rchk@v2
      with:
        run-only: true
