on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yml"
      - "!**revdepcheck.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yml"
      - "!**revdepcheck.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

name: revdep-check

jobs:
  mem-check:
    runs-on: macOS-latest

    name: revdepcheck, macOS, R release

    env:
      _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      _R_CHECK_THINGS_IN_CHECK_DIR_: false
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R dependencies (Windows)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: r-lib/revdepcheck
          needs: revdeps

      - name: Check reverse dependencies
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          revdepcheck::revdep_check(timeout = as.difftime(60, units = 'mins'), num_workers = 4)
          problems <- readLines('revdep/problems.md', warn = FALSE)
          if (length(problems) > 1) stop(paste0(problems, collapse= "\n"))
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: revdep-results
          path: revdep/*.md
